const mongoose = require("mongoose");

const accounttransactionSchema = new mongoose.Schema({
  division_id: {type: mongoose.Schema.Types.ObjectId, ref: "division", required: true},
  branch_name: {type: String, trim: true, required: true},
  type: {type: String, required: true, trim: true},
  category_name: {type: String, required: true, trim: true},
  category_id: {type: mongoose.Schema.Types.ObjectId, ref: "accountcategorys"},
  ledger_id: {type: mongoose.Schema.Types.ObjectId, ref: "accountledger", required: true},
  ledger_name: {type: String, required: true, trim: true},
  ledger_balance: {type: Number},
  transaction_type: {type: String, required: true, trim: true},
  transaction_amount: {type: Number, required: true},
  previous_owe: {type: Number},
  transaction_date: {type: Date, required: true},
  payee_id: {type: mongoose.Schema.Types.ObjectId, ref: "customers"},
  payee_name: {type: String, trim: true},
  payee_mobileno: {type: Number},
  bills: [{
    bill_id: {type: mongoose.Schema.Types.ObjectId, ref: "bill"},
    bill_no: {type: String, trim: true},
    amount: {type: Number},
    amount_allocated: {type: Number},
    balance_due: {type: Number},
  }],
  customer_openingbalance: {
    balance_id: {type: mongoose.Schema.Types.ObjectId, ref: "customeropeningbalances"},
    total_balance: {type: Number},
    amount_allocated: {type: Number},
    pending_balance: {type: Number},
    balance_due: {type: Number},
  },
  user_type: {type: String, trim: true},
  invoice_nos: {type: String, trim: true},
  memo: {type: String, trim: true, required: true},
  cheque_no: {type: String, trim: true},
  serial_no: {type: String, trim: true},
  createduser_type: {type: Number},
  reference_no: {type: String, trim: true},
  balance: {type: Number},
  is_transfer: {type: Boolean, default: false, required: true},
  superadmin_flag: {type: Boolean, default: false},
  superadmin_flag_added_by: {type: String, trim: true},
  superadmin_flag_user: {type: mongoose.Schema.Types.ObjectId, ref: "users"},
  divisionadmin_flag: {type: Boolean, default: false},
  divisionadmin_flag_added_by: {type: String, trim: true},
  divisionadmin_flag_user: {type: mongoose.Schema.Types.ObjectId, ref: "users"},
  created_by: {type: mongoose.Schema.Types.ObjectId, ref: "users", required: true},
  createdstaff_name: {type: String, required: true, trim: true},
  updated_by: {type: mongoose.Schema.Types.ObjectId, ref: "users", required: true},
  updatedstaff_name: {type: String, required: true, trim: true},
  created: {type: Date, required: true}, //* *it will validate the records new or exist record
  updated: {type: Date, default: Date.now},
  is_active: {type: Boolean, default: true, required: true},
  is_deleted: {type: Boolean, default: false, required: true},
});


module.exports = mongoose.model("accounttransaction", accounttransactionSchema);
